# Site
repository: ihwijae/ihwijae.github.io
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 이휘재
title: 신입 백엔드 개발자
email: lhj851@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  ihwijae
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links 추가 링크
# additional_links:
# - title: itsgoingto.be
  # icon: fas fa-globe
  # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile2.jpg
about_content: | # this will include new lines to allow paragraphs
 <mark>지속적인 성장을 위해 노력하는 신입 개발자 입니다</mark><br/> 
  **여자친구의 네일샵 고객관리 프로그램의 불편사항이 제가 개발자가 되기로 한 계기입니다**<br/>
  **첫 번째 사용중인 고객관리 프로그램의 가시성이 좋지 않았고,**<br/>
  **두 번째 네이버 예약과의 연동에 대한 이슈가 있었습니다.**<br/>
  **다른 프로그램을 쓰자니 금액이 비싸다는 문제가 있었고, 여러 방법을 같이 고민하던 중 취미로 내가 한번 만들어보자는 생각으로**<br/>
  **무턱대고 유튜브와 구글을 찾으면서 저의 웹개발 공부가 시작됐습니다.**<br/>
  **HTML과 CSS를 통해 화면의 레이아웃과 틀은 만들었지만 연동과 데이터를 관리 하기 위해선 백엔드 분야에 대해 많은 공부가 필요했습니다. 학원에 들어가 자바를 시작으로 스프링과 DB 기술을 공부하였습니다. 팀프로젝트를 수행하며 개발단계에서 테스트코드를 잘 짜는 것이 중요하다는 생각이 들었고 이점을 유의하며 개발을 하고있습니다.**<br/> 
  **현재는 부족한 CS 지식과 학위를 취득하기 위해 학점은행제 및 방통대학교 과정을 진행 하고 있습니다**<br/>
  **저는 기술의 지속적인 발전과 변화에 뒤처지지 않고, 항상 트렌디하고 혁신적인 개발자로서 성장하고자 합니다.**

content:
  - title: <mark>Project</mark> # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: WorkConGW
        link: https://github.com/jungtaeyeon/WorkConGW
#        link_text: <mark>프로젝트 깃허브</mark>
#        additional_links: 깃허브 아이콘
#          - title: Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
#            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        sub_title: 팀(4인) 팀원
        caption: 2024.01 ~ 2024.03
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: > 
         중소기업의 업무를 도와주는 그룹웨어 서비스
        description: | # this will include new lines to allow paragraphs
          * 일정 관리 메인 페이지에 FullCalendar 라이브러리를 사용하여 캘린더 기능 구현
          * 일정을 조회 할 땐 사용자가 속한 부서 및 팀의 일정, 개인 일정만 조회가 가능하도록 구현
          * 그룹웨어 이므로 권한별로 관리 할 수있는 일정이 다르도록 구현
          * 부서 일정 등록은 부서장만 가능, 일반 사원은 개인일정, 팀일정만 등록 가능하도록 구현
          * 일정의 수정 및 삭제 권한은 일정을 등록한 사용자만 가능하도록 설계
          * 시설 예약 기능 구현 (중복된 시간의 회의실은 조회 및 예약 불가능)
          * 시설 등록은 관리자만 가능하도록 구현, 조회,수정,삭제도 동일
          * 위의 기능은 관리자만 확인할 수 있는 사이드바 메뉴로 보이게 설계
          * 시설 공지, 사용자가 접수 가능한 민원 기능 구현

  - title: <mark>Skill</mark>
    layout: list
    content:
      - layout: left
        title: BackEnd
        description: | # this will include new lines to allow paragraphs
          * Java, Spring, SpringBoot, JSP, JSTL, OracleDB
      - layout: left
        title: FrontEnd
        description: | # this will include new lines to allow paragraphs
          * JavaScript, HTML5, CSS3, JQuery


#  - title: Experience # Title for the section 신입이라 경력 x
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: The Boring Company
#        link: boringcompany.com
#        # link_text: boringcompany.com
#        sub_title: Senior Network System Administrator
#        caption: November 2017 - Present
#        quote: >
#          S
#        description: | # this will include new lines to allow paragraphs


  - title: <mark>Education</mark> # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 구디아카데미
        caption: 2023.09 ~ 2024.03
        link: https://www.gdu.co.kr/main/main.html
        quote:
          클라우드 활용 Java 개발자 교육
        description: | # this will include new lines to allow paragraphs
          * Web Back-End : Java, Spring Pramework, MyBatis
          * Web Front-End (UI) : Html, Css, JavaScript, JQuery, JSP
          * Data Base : Oracle DB
          * Server : Docker, AWS

#  - title: A Little More About Me (외부 활동 내역 아직 x)
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image  -them
#      ![Trees](/modern-resumee/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

